runtime: nodejs20
service: notes-frontend-syarif
instance_class: F1

handlers:
  - url: /
    static_files: dist/index.js
    upload: dist/index.js

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)

default_expiration: "1h"
